"""remove bio field

Revision ID: dd383f7c3d37
Revises: 0d5227ebccdb
Create Date: 2026-01-10 13:44:10.447217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd383f7c3d37'
down_revision = '0d5227ebccdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
